In [18]:
# -*- coding: utf-8 -*-
"""
Predicitve_Analytics.py
"""
#Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import GridSearchCV

def Accuracy(y_true,y_pred):
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float    
    """
    cm = ConfusionMatrix(y_true,y_pred)
    correct = np.trace(cm)
    total = cm.sum()
    acc=0
    if(total>0):
        acc = correct/total
    return acc

def Recall(y_true,y_pred):
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    """
    cm = ConfusionMatrix(y_true,y_pred)
    classes = cm.shape[0]
    col = cm.sum(axis=1)
    sum1=0
    for i in range(classes):
        divisor = col[i]
        if(divisor!=0):
            sum1+=cm[i][i]/divisor
    re=0
    if(classes>0):
        re = sum1/classes
    return re

def Precision(y_true,y_pred):
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float    
    """
    cm = ConfusionMatrix(y_true,y_pred)
    classes = cm.shape[0]
    col = cm.sum(axis=0)
    sum1=0
    for i in range(classes):
        divisor = col[i]
        if(divisor!=0):
            sum1+=cm[i][i]/divisor
    pre=0
    if(classes>0):
        pre = sum1/classes
    return pre

def WCSS(Clusters):
    """
    :Clusters List[numpy.ndarray]
    :rtype: float
    """
def ConfusionMatrix(y_true,y_pred):
    """
    :type y_true: numpy.ndarray
    :type y_pred: numpy.ndarray
    :rtype: float
    """
    #For 0-10 range
    un = np.unique(y_true)
    y_true=y_true-un[0]
    un = np.unique(y_pred)
    y_pred=y_pred-un[0]
    classes = len(np.unique(np.concatenate((y_true,y_pred))))        
    mul = y_true*classes
    sum1 = mul+y_pred    
    x,bins= np.histogram(sum1,bins=np.arange(classes**2+1))
    mat = x.reshape(classes, classes)
    return(mat)

def KNN(X_train,X_test,Y_train, K):
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    :type K: int
   
    :rtype: numpy.ndarray
    """
    #K = 20 #int(input("value of K:"))

    dists = np.sum(X_train**2,axis=1) + np.sum(X_test**2, axis=1)[:, np.newaxis] - 2*np.dot(X_test,X_train.T)

    sorted_distance = np.argsort(dists, axis=1)

    top_k_neigh = sorted_distance[:,:K]
   
    pred_labels = []
    for i in top_k_neigh:
        c, cot = np.unique(Y_train[i], return_counts = True)
        ind = np.argmax(cot)
        pred_labels.append(c[ind])

    pred_labels = np.asarray(pred_labels)

    return pred_labels

def RandomForest(X_train,Y_train,X_test):
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: numpy.ndarray
    """
    
def PCA(X_train,N):
    """
    :type X_train: numpy.ndarray
    :type N: int
    :rtype: numpy.ndarray
    """
    #standardizing data 
    sc = StandardScaler()
    std_data = sc.fit_transform(X_train)
    pca_data = pd.DataFrame(std_data)

    #Construct Covariance Matrix(C)
    transpose_data = pca_data.T
    C = np.cov(transpose_data)


    #Decomposing C to eigen vectors and values
    e_val, e_vec =  np.linalg.eig(C)


    #N = int(input("Reduced Deminsions:")) ------ Passed on to tge function

    #Estimating High-valued Eigen vectors
    eval_sorted = np.argsort(e_val)
    top_evals = eval_sorted[::-1][:N]
    high_valued_vectors = e_vec[:,top_evals]

    PCA = np.empty([pca_data.shape[0], high_valued_vectors.shape[1]])
    i = 0
    for v in high_valued_vectors.T:
            PCA[:,i] = np.dot(pca_data, v.T)
            i += 1
    return PCA
    
#TODO: Rename to Kmeans
def Kmeans_py(X_train,N):
    """
    :type X_train: numpy.ndarray
    :type N: int
    :rtype: List[numpy.ndarray]
    """    
    #Parameters
    labels = np.zeros(train_y.shape) #Initial assignment of labels
    centroids = X_train[np.random.choice(X_train.shape[0], N, replace=False)] #Random initialization of centroids
    old_centroids = X_train[np.random.choice(X_train.shape[0], N, replace=False)] #Random initialization of centroids
    
    clusters = [[] for x in range(N)]
    max_iter = 200

    for iteration in range(max_iter):
        iteration += 1
        old_centroids = centroids
        
        #Calculating the euclidean distance of datapoints to the centroids
        dist = np.zeros((N, X_train.shape[0]))
        for i in range(len(centroids)):
            dist[i] = np.linalg.norm(X_train - old_centroids[i], axis=1)
        
        dist = dist.transpose()
        labels = np.argmin(dist, axis=1)
        
        #Clustering of datapoint based on euclidean distance to centroids
        cls_ind = [[] for x in range(N)]
        for l in range(N):
            cls_ind[l] = [i for i,x in enumerate(labels) if x == l]
        
        clstr = [[] for x in range(N)]
        for i in range(N):
            clstr[i] = [X_train[idx] for idx in cls_ind[i]]
            
        clstr = np.array(clstr)
        for i in range(N):
            centroids[i] = np.mean(clstr[i])
        clusters = clstr
    return clusters
    
def SVM(X_train,Y_train,X_test):
    DIC_svm =  SVC(kernel='linear',gamma='scale')
    DIC_svm.fit(X_train,Y_train)
    return(DIC_svm.predict(X_test))
   
def LR(X_train,Y_train,X_test):
    DIC_logisticRegression = LogisticRegression(solver='lbfgs',multi_class='auto',max_iter=7500)
    DIC_logisticRegression.fit(X_train,Y_train)
    return(DIC_logisticRegression.predict(X_test))

def DT(X_train,Y_train,X_test):
    DIC_decisionTreeClassifier = DecisionTreeClassifier()
    DIC_decisionTreeClassifier.fit(X_train,Y_train)
    print("Depth")
    print(DIC_decisionTreeClassifier.tree_.max_depth)
    return(DIC_decisionTreeClassifier.predict(X_test))

def KNN_sk(X_train,Y_train,X_test,k=7):
    DIC_KNN = KNeighborsClassifier(n_neighbors=k)
    DIC_KNN.fit(X_train,Y_train)
    KNNResult = DIC_KNN.predict(X_test)
    return DIC_KNN.predict(X_test)

def ensemble(X_train,Y_train,X_test):
    classifierSVC = SVC(kernel='linear')
    classifierLR = LogisticRegression(solver='lbfgs',multi_class='auto',max_iter=7500)
    classifierDT = DecisionTreeClassifier()
    classifierKNN = KNeighborsClassifier(n_neighbors=250)    
    ensembleVC = VotingClassifier(estimators=[("SVM",classifierSVC),("LR",classifierLR),
                                              ("DT",classifierDT),("KNN",classifierKNN)],voting='hard')
    ensembleVC.fit(X_train,Y_train)
    return(ensembleVC.predict(X_test))

#def SklearnSupervisedLearning(X_train,Y_train,X_test):
def SklearnSupervisedLearning(X_train,Y_train,X_test,Y_test):
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray    
    :rtype: List[numpy.ndarray] 
    """    
    N,C= X_test.shape
    result = []
     
    #SVM 
    SVMResult = SVM(X_train,Y_train,X_test)
    print("SVM accuracy : %f" %Accuracy(Y_test,SVMResult))
    result.append(SVMResult)
    
    #LR
    LRResult = LR(X_train,Y_train,X_test)
    print("Logisitic Regression accuracy : %f" %Accuracy(Y_test,LRResult))
    result.append(LRResult)
    
    #Decision Tree
    DTResult = DT(X_train,Y_train,X_test)
    print("Decision Tree accuracy : %f" %Accuracy(Y_test,DTResult))
    result.append(DTResult)
    
    #KNN
    KNNResult = KNN_sk(X_train,Y_train,X_test)
    result.append(KNNResult)
    
    return result
    
#def SklearnVotingClassifier(X_train,Y_train,X_test):
def SklearnVotingClassifier(X_train,Y_train,X_test,Y_test):    
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray    
    :rtype: List[numpy.ndarray] 
    """
    ensembleResult = ensemble(X_train,Y_train,X_test)
    print("Voting Classifier accuracy : %f" %ensembleVC.score(X_test,Y_test))
    return ensembleResult

def subPlotConfusionMatrixElement(ax,confusionMatrix,text):
    ax.matshow(confusionMatrix)
    ax.title.set_text(text)
    ax.xaxis.set_ticks_position('bottom')
    
def PlotConfusionMatrix(X_train,Y_train,X_test,Y_test):
    """
    SVMResult = SVM(X_train,Y_train,X_test)
    LRResult = LR(X_train,Y_train,X_test)
    DTResult = DT(X_train,Y_train,X_test)
    KNNResult = KNN_sk(X_train,Y_train,X_test,Y_test)
    ensembleResult = ensemble(X_train,Y_train,X_test)
    """
    #TODO- Remove. Only for testing.
    SVMResult = DT(X_train,Y_train,X_test)
    LRResult = SVMResult
    DTResult = SVMResult
    KNNResult = SVMResult
    ensembleResult = SVMResult      

    cmSVM = ConfusionMatrix(Y_test,SVMResult)
    cmLR = ConfusionMatrix(Y_test,LRResult)
    cmDT = ConfusionMatrix(Y_test,DTResult)
    cmKNN = ConfusionMatrix(Y_test,KNNResult)
    cmEnsemble = ConfusionMatrix(Y_test,ensembleResult)
    
    fig, ax = plt.subplots(1, 5, sharex='col', sharey='row',figsize=(15, 4))
    plt.suptitle('Confusion matrix Plots')
    
    subPlotConfusionMatrixElement(ax[0],cmSVM,"SVM")
    subPlotConfusionMatrixElement(ax[1],cmLR,"Logistic Regression")
    subPlotConfusionMatrixElement(ax[2],cmDT,"Decision Tree")
    subPlotConfusionMatrixElement(ax[3],cmKNN,"K Nearest Neighbors")
    subPlotConfusionMatrixElement(ax[4],cmEnsemble,"Ensemble")
    
    #print(fig)
    
def PlotGridSearchElement(ax,plt_X,plt_Y,title):
    ax.plot(plt_X,plt_Y)
    ax.title.set_text(title)
    
def GridSearchUtil(X_train, Y_train,function,tuned_parameters):
    gridSearch = GridSearchCV(function, tuned_parameters,cv=5)
    gridSearch.fit(X_train, Y_train) 
    return(gridSearch.cv_results_['mean_test_score'])

def GridSearch(X_train,Y_train,X_test,Y_test):

    fig, ax = plt.subplots(1, 3, sharex='col', sharey='row',figsize=(15, 4))
    plt.suptitle('Grid Search Parameters Plot')
    
    plt_X = [1,5,10,15]
    tuned_parameters = [{'C': plt_X}]
    plt_Y = GridSearchUtil(X_train, Y_train,SVC(kernel='linear',gamma='scale'),tuned_parameters)
    PlotGridSearchElement(ax[0],plt_X,plt_Y,"SVM")
    
    plt_X = [5,10,15,20]
    tuned_parameters = [{'max_depth': plt_X}]
    plt_Y = GridSearchUtil(X_train, Y_train,DecisionTreeClassifier(),tuned_parameters)
    PlotGridSearchElement(ax[1],plt_X,plt_Y,"Decision Tree")
    
    plt_X = [2,10,15,20]
    tuned_parameters = [{'n_neighbors': plt_X}]
    plt_Y = GridSearchUtil(X_train, Y_train,KNeighborsClassifier(),tuned_parameters)
    PlotGridSearchElement(ax[2],plt_X,plt_Y,"K Nearest Neighbors")
    


In [19]:
#Reading datafile
data = pd.read_csv("data.csv", header = None)
data = data.drop(index=0) #Drops the column names
#print(data.shape) #dimensions of the data
#print(data)

#Features and label extraction
data_x = data.iloc[:, :48] #Features
data_y = data.iloc[:, 48] #Labels
from sklearn import preprocessing
MinMaxScaler = preprocessing.MinMaxScaler()
data_x = MinMaxScaler.fit_transform(data_x)

#Splittiing data into train (80%) and test (20%)
train_X, test_X, train_y, test_y = train_test_split(data_x, data_y, test_size = 0.2)
#print(data.columns.values)



In [20]:
#API Calls
SklearnSupervisedLearning(train_X,train_y,test_X,test_y)
#SklearnVotingClassifier(train_X,train_y,test_X,test_y)
#PlotConfusionMatrix(train_X,train_y,test_X,test_y)
#GridSearch(train_X,train_y,test_X,test_y)

SVM accuracy : 0.891357
Logisitic Regression accuracy : 0.871460
Depth
32
Decision Tree accuracy : 0.982910


[array([10, 11,  8, ...,  4,  1,  7], dtype=int64),
 array([10, 11,  8, ...,  4,  1,  7], dtype=int64),
 array([ 2, 11,  8, ...,  4,  1,  7], dtype=int64),
 array([ 2, 11,  8, ...,  4,  1,  7], dtype=int64)]

In [87]:
#Testing our and skLearn performance
def test(X_train,Y_train,X_test,Y_test):
    SVMResult = DT(X_train,Y_train,X_test)
    print("SKLearn")
    from sklearn.metrics import confusion_matrix,accuracy_score
    #from sklearn.metrics import classification_report
    #print(classification_report(Y_test,SVMResult))
    from sklearn.metrics import precision_score
    print(precision_score(Y_test,SVMResult, average='macro'))
    from sklearn.metrics import recall_score
    print(recall_score(Y_test,SVMResult, average='macro'))
    from sklearn.cluster import KMeans
    k = len(np.unique(Y_train))
    kmeans = KMeans(n_clusters=k, random_state=0).fit(Y_train.values.reshape(-1, 1))
    a = kmeans.labels_
    print("KMeans")
    print(kmeans.labels_)
    print("KNN accuracy")
    kr = KNN_sk(X_train,Y_train,X_test,15)
    print(Accuracy(Y_test,kr))

    cmSVM1 = ConfusionMatrix(Y_test,SVMResult)
    print("Our")
    print(cmSVM1)
    print(Accuracy(Y_test,SVMResult))
    print(Precision(Y_test,SVMResult))
    print(Recall(Y_test,SVMResult))
    print("KMeans")
    cluster_list = Kmeans(Y_train,k)
    print(cluster_list)
    print("KNN accuracy")
    kr = KNN(X_train,X_test,Y_train, 15)
    print(Accuracy(Y_test,kr))  



In [88]:
test(train_X,train_y,test_X,test_y)

SKLearn
[[719   0   0   0   0  15   0   0   4   0   0]
 [  0 718   0   0   1   0   0   0   1  17   0]
 [  0   0 731   0   7   0   0   0   1   0   0]
 [  0   0   4 716   1   0   0   3   0   0   0]
 [  0   1  11   2 720   0   0  14   0   0   0]
 [ 18   2   0   0   0 718   0   0   9   0   0]
 [  0   0   0   0   0   0 753   0   0   0   0]
 [  0   0   0   1  17   0   0 692   0   0   0]
 [  5   0   0   0   0  13   0   0 736   1   0]
 [  0  16   0   0   0   0   0   0   0 760   0]
 [  0   0   0   0   0   0   0   0   0   0 765]]
0.97998046875
0.9799517906805928
0.9799280042901746
KMeans
[ 8  6  3 ...  3 10  0]
KNN accuracy
0.982177734375
Our
[[719   0   0   0   0  15   0   0   4   0   0]
 [  0 718   0   0   1   0   0   0   1  17   0]
 [  0   0 731   0   7   0   0   0   1   0   0]
 [  0   0   4 716   1   0   0   3   0   0   0]
 [  0   1  11   2 720   0   0  14   0   0   0]
 [ 18   2   0   0   0 718   0   0   9   0   0]
 [  0   0   0   0   0   0 753   0   0   0   0]
 [  0   0   0   1  17   0   0 

C:\Users\sande\Anaconda3\lib\site-packages\pandas\core\series.py:1143: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


0.090087890625
